language: generic
sudo: false # use container based build

# set clone depth to false to make sure that conda build can write the
# correct GIT_BUILD_STR
git:
  depth: false

env:
    matrix:
        # python 3.8
        - PYTHON_VERSION=3.8 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.8 XARRAY_VERSION=0.15
        - PYTHON_VERSION=3.8 XARRAY_VERSION=0.14
        - PYTHON_VERSION=3.8 USE_PIP=true
        # python 3.7
        - PYTHON_VERSION=3.7 DEPLOY_CONDA=true
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.14
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.13
        - PYTHON_VERSION=3.7 XARRAY_VERSION=0.12
    global:
        secure: "cU0AKSwMJDE4kSPdohXX86URKIlVbbLjxJvwyL7T5pu1L+s4ZM6CxHRalUks2N/JSBefnpl2UokIpTePYKS2t1Xn7MKUaFOtLlA22lqz7JFuM9q0qQewtZLheMXClx6QhcZey78aE+oU8dG0RT5GKYPXyznGP41JSXKdOHiwj8sbHhYy1iJcUaKa7AoFYoQgnyhi+oobDm6neUvg9RHN3OwtSALAy2CjHs/fVUEImM14XXsg4WfjHfuNr3vBNSOHNfnXc+sqUOEyxKmb8Q45AElkueMLOt6x2TvKDByHQdQybQ0jBkByHGZ48us1Tx5N+Swwg9+KUVp2Aj8wom/im721exdUC5+sC6bZnp75vSVKk4jgpVU89FTJV57FGfTZzvu032+ybJgs4g3lBb+c1TkbYLJzlZqxZVy29vKZNGjFH553wtFxXJLBOr60ka7xj1o7x4s7IsVCsxRzBOaCcCRKY2B5HJMpw5lMzf/nvWNz38uT2Qw8EduhGxKOfbCew2NSmIZB8JoL0U6UfrETlurAgttKZO6ff7TAb7hICpuZagnovIA1Ve1GPmYj1Ste5C0WxEdWFTog+py3ki4mOXi9BxsbN0Ir8f/VyX67s3uA6kMaZRppauSXEvKEM5LBtIZdB7p4pfqMpbm1TC1whK12/lBWFn/12+FqEHi27Lg="
os:
    - linux
    - osx

services:
    - xvfb

matrix:
    allow_failures:
        - env: PYTHON_VERSION=3.8 USE_PIP=true

before_install:
    - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then export DEPLOY_CONDA=false; fi
    # Remove homebrew.
    - |
      if [[ $TRAVIS_OS_NAME == "osx" ]]; then
          echo ""
          echo "Removing homebrew from Travis CI to avoid conflicts."
          curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
          chmod +x ~/uninstall_homebrew
          ~/uninstall_homebrew -fq
          rm ~/uninstall_homebrew
      fi
    # define functions to unset and reset encrypted variables
    - function unset_secure {
          CONDA_TOKEN_SAVE=$CONDA_REPO_TOKEN;
          unset CONDA_REPO_TOKEN;
          }
    - function reset_secure {
          export CONDA_REPO_TOKEN=$CONDA_TOKEN_SAVE;
          }
    - unset_secure
    # increase open files limit
    - ulimit -a
    - ulimit -Sn 10000
    - ulimit -a
      # select the os name for the conda installer
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
          OS_NAME=MacOSX;
      else
          OS_NAME=Linux;
      fi
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-${OS_NAME}-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -bp $HOME/miniconda3
    - source $HOME/miniconda3/bin/activate root
    - hash -r
    - reset_secure

before_script:
    - if [[ $TRAVIS_OS_NAME == "linux" ]]; then
          export "DISPLAY=:99.0";
          sh -e /etc/init.d/xvfb start;
          sleep 3;
      fi

install:
    # unset the global CONDA_REPO_TOKEN variable because it is not needed
    # during the tests. This decreases the vulnerability
    - unset_secure
    - |
        echo ""
        echo "Configuring conda."
        conda config --set always_yes yes --set changeps1 no
        conda config --add channels conda-forge
        conda config --add channels chilipp
        conda update -q conda
        conda install conda-build anaconda-client conda-verify
    - if [[ $TRAVIS_TAG == "" ]]; then
        export GIT_BRANCH=$TRAVIS_BRANCH;
        conda config --add channels chilipp/label/${TRAVIS_BRANCH};
      fi
    - python ci/setup_append.py ci/conda-recipe xarray=${XARRAY_VERSION}
    - if [[ $USE_PIP == true ]]; then
        python -m pip install . -r ci/requirements.txt;
      fi
    - conda info -a
    - conda list
    - reset_secure
script:
    - unset_secure
    # install conda
    - if [[ $USE_PIP == true ]]; then
          pytest -v --cov=psyplot && codecov;
      else
          conda build ci/conda-recipe --python $PYTHON_VERSION;
      fi
    # export the pw to make it available for the deploy
    - reset_secure
    # deploy here (don't use travis deploy because it requires homebrew)
    - if [[ $DEPLOY_CONDA == "true" && $TRAVIS_PULL_REQUEST == "false" && $TRAVIS_REPO_SLUG == "psyplot/psyplot" ]]; then
          ci/deploy_anaconda.py;
      fi
