environment:

  PYTHON_ARCH: "64"
  PYTHON: "C:\\Miniconda36-x64"

  matrix:
    - PYTHON_VERSION: "3.7"
      XARRAY_VERSION: "0.14"
      BUILD_STR_END: cf
    - PYTHON_VERSION: "3.7"
    - PYTHON_VERSION: "3.8"
      XARRAY_VERSION: "0.15"
      BUILD_STR_END: cf

install:
    # windows config (for installation)
    - cmd: "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - cmd: setlocal
    - cmd: set CONDA_REPO_TOKEN=
    # conda config
    - conda config --set always_yes yes --set changeps1 no
    - conda update -q conda
    - conda install conda-build anaconda-client
    - IF NOT DEFINED BUILD_STR_END (conda config --add channels chilipp) ELSE (conda config --add channels conda-forge)
    - conda config --add channels psyplot
    - conda info -a
    - conda list
    # windows config
    - cmd: endlocal
    - cmd: 'SET PYTHONWARNINGS=ignore:mode:DeprecationWarning:docutils.io:245'
    - cmd: "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (SET GIT_BRANCH=%APPVEYOR_REPO_BRANCH%)"
    - cmd: "IF NOT DEFINED APPVEYOR_REPO_TAG_NAME (conda config --add channels psyplot/label/%APPVEYOR_REPO_BRANCH%)"
    - cmd: python ci\\setup_append.py ci\\conda-recipe xarray=%XARRAY_VERSION%

build: off

test_script:
    - cmd: setlocal
    - cmd: set CONDA_REPO_TOKEN=
    - cmd: conda build ci/conda-recipe --python %PYTHON_VERSION%
    - cmd: endlocal

deploy_script:
    - cmd: "python ci\\deploy_anaconda.py"
